# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'jingluzi.com|京鹿子动漫模玩'
description: 'jingluzi.com|京鹿子日本代购正版模玩'
permalink: pretty
logo: "https://img.alicdn.com/imgextra/i3/2710706468/O1CN01O5yoSo1xeOLwOfoCO_!!2710706468.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: 首页Home
  url: /
- title: 关于About
  url: /about/
- title: 联系Contact
  url: /contact/
- title: 博客Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: 回到顶部 ↑ Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: 博客|Posts
    output: true
    description: "我的思考和想法都会写在这里|My thoughts and ideas"
    feature_text: 欢迎访问我的博客| Welcome to my blog
    feature_image: "https://img.alicdn.com/imgextra/i4/2710706468/O1CN01yqV5rH1xeOQTOT2Js_!!2710706468.jpg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
